wget http://www.iwik.org/ipcountry/AD.cidr
wget http://www.iwik.org/ipcountry/AE.cidr
wget http://www.iwik.org/ipcountry/AF.cidr
wget http://www.iwik.org/ipcountry/AG.cidr
wget http://www.iwik.org/ipcountry/AI.cidr
wget http://www.iwik.org/ipcountry/AL.cidr
wget http://www.iwik.org/ipcountry/AM.cidr
wget http://www.iwik.org/ipcountry/AO.cidr
wget http://www.iwik.org/ipcountry/AP.cidr
wget http://www.iwik.org/ipcountry/AR.cidr
wget http://www.iwik.org/ipcountry/AS.cidr
wget http://www.iwik.org/ipcountry/AT.cidr
wget http://www.iwik.org/ipcountry/AU.cidr
wget http://www.iwik.org/ipcountry/AW.cidr
wget http://www.iwik.org/ipcountry/AX.cidr
wget http://www.iwik.org/ipcountry/AZ.cidr
wget http://www.iwik.org/ipcountry/BA.cidr
wget http://www.iwik.org/ipcountry/BB.cidr
wget http://www.iwik.org/ipcountry/BD.cidr
wget http://www.iwik.org/ipcountry/BE.cidr
wget http://www.iwik.org/ipcountry/BF.cidr
wget http://www.iwik.org/ipcountry/BG.cidr
wget http://www.iwik.org/ipcountry/BH.cidr
wget http://www.iwik.org/ipcountry/BI.cidr
wget http://www.iwik.org/ipcountry/BJ.cidr
wget http://www.iwik.org/ipcountry/BL.cidr
wget http://www.iwik.org/ipcountry/BM.cidr
wget http://www.iwik.org/ipcountry/BN.cidr
wget http://www.iwik.org/ipcountry/BO.cidr
wget http://www.iwik.org/ipcountry/BQ.cidr
wget http://www.iwik.org/ipcountry/BR.cidr
wget http://www.iwik.org/ipcountry/BS.cidr
wget http://www.iwik.org/ipcountry/BT.cidr
wget http://www.iwik.org/ipcountry/BW.cidr
wget http://www.iwik.org/ipcountry/BY.cidr
wget http://www.iwik.org/ipcountry/BZ.cidr
wget http://www.iwik.org/ipcountry/CA.cidr
wget http://www.iwik.org/ipcountry/CD.cidr
wget http://www.iwik.org/ipcountry/CF.cidr
wget http://www.iwik.org/ipcountry/CG.cidr
wget http://www.iwik.org/ipcountry/CH.cidr
wget http://www.iwik.org/ipcountry/CI.cidr
wget http://www.iwik.org/ipcountry/CK.cidr
wget http://www.iwik.org/ipcountry/CL.cidr
wget http://www.iwik.org/ipcountry/CM.cidr
wget http://www.iwik.org/ipcountry/CN.cidr
wget http://www.iwik.org/ipcountry/CO.cidr
wget http://www.iwik.org/ipcountry/CR.cidr
wget http://www.iwik.org/ipcountry/CU.cidr
wget http://www.iwik.org/ipcountry/CV.cidr
wget http://www.iwik.org/ipcountry/CW.cidr
wget http://www.iwik.org/ipcountry/CY.cidr
wget http://www.iwik.org/ipcountry/CZ.cidr
wget http://www.iwik.org/ipcountry/DE.cidr
wget http://www.iwik.org/ipcountry/DJ.cidr
wget http://www.iwik.org/ipcountry/DK.cidr
wget http://www.iwik.org/ipcountry/DM.cidr
wget http://www.iwik.org/ipcountry/DO.cidr
wget http://www.iwik.org/ipcountry/DZ.cidr
wget http://www.iwik.org/ipcountry/EC.cidr
wget http://www.iwik.org/ipcountry/EE.cidr
wget http://www.iwik.org/ipcountry/EG.cidr
wget http://www.iwik.org/ipcountry/ER.cidr
wget http://www.iwik.org/ipcountry/ES.cidr
wget http://www.iwik.org/ipcountry/ET.cidr
wget http://www.iwik.org/ipcountry/EU.cidr
wget http://www.iwik.org/ipcountry/FI.cidr
wget http://www.iwik.org/ipcountry/FJ.cidr
wget http://www.iwik.org/ipcountry/FK.cidr
wget http://www.iwik.org/ipcountry/FM.cidr
wget http://www.iwik.org/ipcountry/FO.cidr
wget http://www.iwik.org/ipcountry/FR.cidr
wget http://www.iwik.org/ipcountry/GA.cidr
wget http://www.iwik.org/ipcountry/GB.cidr
wget http://www.iwik.org/ipcountry/GD.cidr
wget http://www.iwik.org/ipcountry/GE.cidr
wget http://www.iwik.org/ipcountry/GF.cidr
wget http://www.iwik.org/ipcountry/GG.cidr
wget http://www.iwik.org/ipcountry/GH.cidr
wget http://www.iwik.org/ipcountry/GI.cidr
wget http://www.iwik.org/ipcountry/GL.cidr
wget http://www.iwik.org/ipcountry/GM.cidr
wget http://www.iwik.org/ipcountry/GN.cidr
wget http://www.iwik.org/ipcountry/GP.cidr
wget http://www.iwik.org/ipcountry/GQ.cidr
wget http://www.iwik.org/ipcountry/GR.cidr
wget http://www.iwik.org/ipcountry/GT.cidr
wget http://www.iwik.org/ipcountry/GU.cidr
wget http://www.iwik.org/ipcountry/GW.cidr
wget http://www.iwik.org/ipcountry/GY.cidr
wget http://www.iwik.org/ipcountry/HK.cidr
wget http://www.iwik.org/ipcountry/HN.cidr
wget http://www.iwik.org/ipcountry/HR.cidr
wget http://www.iwik.org/ipcountry/HT.cidr
wget http://www.iwik.org/ipcountry/HU.cidr
wget http://www.iwik.org/ipcountry/ID.cidr
wget http://www.iwik.org/ipcountry/IE.cidr
wget http://www.iwik.org/ipcountry/IL.cidr
wget http://www.iwik.org/ipcountry/IM.cidr
wget http://www.iwik.org/ipcountry/IN.cidr
wget http://www.iwik.org/ipcountry/IO.cidr
wget http://www.iwik.org/ipcountry/IQ.cidr
wget http://www.iwik.org/ipcountry/IR.cidr
wget http://www.iwik.org/ipcountry/IS.cidr
wget http://www.iwik.org/ipcountry/IT.cidr
wget http://www.iwik.org/ipcountry/JE.cidr
wget http://www.iwik.org/ipcountry/JM.cidr
wget http://www.iwik.org/ipcountry/JO.cidr
wget http://www.iwik.org/ipcountry/JP.cidr
wget http://www.iwik.org/ipcountry/KE.cidr
wget http://www.iwik.org/ipcountry/KG.cidr
wget http://www.iwik.org/ipcountry/KH.cidr
wget http://www.iwik.org/ipcountry/KI.cidr
wget http://www.iwik.org/ipcountry/KM.cidr
wget http://www.iwik.org/ipcountry/KN.cidr
wget http://www.iwik.org/ipcountry/KP.cidr
wget http://www.iwik.org/ipcountry/KR.cidr
wget http://www.iwik.org/ipcountry/KW.cidr
wget http://www.iwik.org/ipcountry/KY.cidr
wget http://www.iwik.org/ipcountry/KZ.cidr
wget http://www.iwik.org/ipcountry/LA.cidr
wget http://www.iwik.org/ipcountry/LB.cidr
wget http://www.iwik.org/ipcountry/LC.cidr
wget http://www.iwik.org/ipcountry/LI.cidr
wget http://www.iwik.org/ipcountry/LK.cidr
wget http://www.iwik.org/ipcountry/LR.cidr
wget http://www.iwik.org/ipcountry/LS.cidr
wget http://www.iwik.org/ipcountry/LT.cidr
wget http://www.iwik.org/ipcountry/LU.cidr
wget http://www.iwik.org/ipcountry/LV.cidr
wget http://www.iwik.org/ipcountry/LY.cidr
wget http://www.iwik.org/ipcountry/MA.cidr
wget http://www.iwik.org/ipcountry/MC.cidr
wget http://www.iwik.org/ipcountry/MD.cidr
wget http://www.iwik.org/ipcountry/ME.cidr
wget http://www.iwik.org/ipcountry/MF.cidr
wget http://www.iwik.org/ipcountry/MG.cidr
wget http://www.iwik.org/ipcountry/MH.cidr
wget http://www.iwik.org/ipcountry/MK.cidr
wget http://www.iwik.org/ipcountry/ML.cidr
wget http://www.iwik.org/ipcountry/MM.cidr
wget http://www.iwik.org/ipcountry/MN.cidr
wget http://www.iwik.org/ipcountry/MO.cidr
wget http://www.iwik.org/ipcountry/MP.cidr
wget http://www.iwik.org/ipcountry/MQ.cidr
wget http://www.iwik.org/ipcountry/MR.cidr
wget http://www.iwik.org/ipcountry/MS.cidr
wget http://www.iwik.org/ipcountry/MT.cidr
wget http://www.iwik.org/ipcountry/MU.cidr
wget http://www.iwik.org/ipcountry/MV.cidr
wget http://www.iwik.org/ipcountry/MW.cidr
wget http://www.iwik.org/ipcountry/MX.cidr
wget http://www.iwik.org/ipcountry/MY.cidr
wget http://www.iwik.org/ipcountry/MZ.cidr
wget http://www.iwik.org/ipcountry/NA.cidr
wget http://www.iwik.org/ipcountry/NC.cidr
wget http://www.iwik.org/ipcountry/NE.cidr
wget http://www.iwik.org/ipcountry/NF.cidr
wget http://www.iwik.org/ipcountry/NG.cidr
wget http://www.iwik.org/ipcountry/NI.cidr
wget http://www.iwik.org/ipcountry/NL.cidr
wget http://www.iwik.org/ipcountry/NO.cidr
wget http://www.iwik.org/ipcountry/NP.cidr
wget http://www.iwik.org/ipcountry/NR.cidr
wget http://www.iwik.org/ipcountry/NU.cidr
wget http://www.iwik.org/ipcountry/NZ.cidr
wget http://www.iwik.org/ipcountry/OM.cidr
wget http://www.iwik.org/ipcountry/PA.cidr
wget http://www.iwik.org/ipcountry/PE.cidr
wget http://www.iwik.org/ipcountry/PF.cidr
wget http://www.iwik.org/ipcountry/PG.cidr
wget http://www.iwik.org/ipcountry/PH.cidr
wget http://www.iwik.org/ipcountry/PK.cidr
wget http://www.iwik.org/ipcountry/PL.cidr
wget http://www.iwik.org/ipcountry/PM.cidr
wget http://www.iwik.org/ipcountry/PR.cidr
wget http://www.iwik.org/ipcountry/PS.cidr
wget http://www.iwik.org/ipcountry/PT.cidr
wget http://www.iwik.org/ipcountry/PW.cidr
wget http://www.iwik.org/ipcountry/PY.cidr
wget http://www.iwik.org/ipcountry/QA.cidr
wget http://www.iwik.org/ipcountry/RE.cidr
wget http://www.iwik.org/ipcountry/RO.cidr
wget http://www.iwik.org/ipcountry/RS.cidr
wget http://www.iwik.org/ipcountry/RU.cidr
wget http://www.iwik.org/ipcountry/RW.cidr
wget http://www.iwik.org/ipcountry/SA.cidr
wget http://www.iwik.org/ipcountry/SB.cidr
wget http://www.iwik.org/ipcountry/SC.cidr
wget http://www.iwik.org/ipcountry/SD.cidr
wget http://www.iwik.org/ipcountry/SE.cidr
wget http://www.iwik.org/ipcountry/SG.cidr
wget http://www.iwik.org/ipcountry/SI.cidr
wget http://www.iwik.org/ipcountry/SK.cidr
wget http://www.iwik.org/ipcountry/SL.cidr
wget http://www.iwik.org/ipcountry/SM.cidr
wget http://www.iwik.org/ipcountry/SN.cidr
wget http://www.iwik.org/ipcountry/SO.cidr
wget http://www.iwik.org/ipcountry/SR.cidr
wget http://www.iwik.org/ipcountry/SS.cidr
wget http://www.iwik.org/ipcountry/ST.cidr
wget http://www.iwik.org/ipcountry/SV.cidr
wget http://www.iwik.org/ipcountry/SX.cidr
wget http://www.iwik.org/ipcountry/SY.cidr
wget http://www.iwik.org/ipcountry/SZ.cidr
wget http://www.iwik.org/ipcountry/TC.cidr
wget http://www.iwik.org/ipcountry/TD.cidr
wget http://www.iwik.org/ipcountry/TG.cidr
wget http://www.iwik.org/ipcountry/TH.cidr
wget http://www.iwik.org/ipcountry/TJ.cidr
wget http://www.iwik.org/ipcountry/TK.cidr
wget http://www.iwik.org/ipcountry/TL.cidr
wget http://www.iwik.org/ipcountry/TM.cidr
wget http://www.iwik.org/ipcountry/TN.cidr
wget http://www.iwik.org/ipcountry/TO.cidr
wget http://www.iwik.org/ipcountry/TR.cidr
wget http://www.iwik.org/ipcountry/TT.cidr
wget http://www.iwik.org/ipcountry/TV.cidr
wget http://www.iwik.org/ipcountry/TW.cidr
wget http://www.iwik.org/ipcountry/TZ.cidr
wget http://www.iwik.org/ipcountry/UA.cidr
wget http://www.iwik.org/ipcountry/UG.cidr
wget http://www.iwik.org/ipcountry/UM.cidr
wget http://www.iwik.org/ipcountry/US.cidr
wget http://www.iwik.org/ipcountry/UY.cidr
wget http://www.iwik.org/ipcountry/UZ.cidr
wget http://www.iwik.org/ipcountry/VA.cidr
wget http://www.iwik.org/ipcountry/VC.cidr
wget http://www.iwik.org/ipcountry/VE.cidr
wget http://www.iwik.org/ipcountry/VG.cidr
wget http://www.iwik.org/ipcountry/VI.cidr
wget http://www.iwik.org/ipcountry/VN.cidr
wget http://www.iwik.org/ipcountry/VU.cidr
wget http://www.iwik.org/ipcountry/WF.cidr
wget http://www.iwik.org/ipcountry/WS.cidr
wget http://www.iwik.org/ipcountry/YE.cidr
wget http://www.iwik.org/ipcountry/YT.cidr
wget http://www.iwik.org/ipcountry/ZA.cidr
wget http://www.iwik.org/ipcountry/ZM.cidr
wget http://www.iwik.org/ipcountry/ZW.cidr

